name: GitHub Actions Demo
on:
 push:
   branches: [ main ]
   paths-ignore: [.github/**]

 workflow_dispatch:
jobs:
  Build:
    runs-on: alpine-latest
    steps:
      - run: |
          echo "event: ${{ github.event_name }}"
          echo "branch: ${{ github.ref }}"
          cat /etc/os-release
      - uses: actions/checkout@v3.3.0
      - name: list repo files
        run: |
          echo "${{ github.repository }} files..."
          tree
          
